### ISSUE TITLE
【0188_Week 02】第二周总结

### ISSUE THREAD

**Issue by zfben** [algorithm005-class01/algorithm005-class01#412]
### 深度优先遍历（DFS）

前序（Pre-order）: 根-左-右
中序（In-order）: 左-根-右
后序（Post-order）: 左-右-根

### 广度优先遍历（BFS）

每一层从左到右遍历

### 查询

因为有序，所以查找时为二分查找，时间复杂度为O（logn）

### 插入

先查找，如果找不到，最后查找的结点就是要插入的位置

### 删除

如果删除的结点是叶子结点，并且没有子结点，找到后删除即可。
如果删除的结点有叶子结点，将此结点删除后，将该结点的右子树的最小的结点替换该结点即可。

### 递归的代码模板

1. 递归终结条件
2. 处理当前层逻辑
3. 下探到下一层
4. 清理当前层

- 不要人肉进行递归
- 找到最近最简方法、将其拆解成可重复解决的问题
- 数学归纳法思维

**Comment by manajay** [comment]
二叉树的删除 第二点不严谨, 你说的是删除节点存在左右子树的情况,
还有一种情况是如果仅仅只存在左子树或者右子树,其实仅仅需要将节点的父节点指向删除节点子树的节点即可
