### ISSUE TITLE
【0294_week 00】预习课第一课观后感--有多少人要留下Flag

### ISSUE THREAD

**Issue by daxingshen** [algorithm005-class01/algorithm005-class01#59]
![image](https://user-images.githubusercontent.com/23305617/70384193-f0537e00-19b5-11ea-8b29-d41e11dce635.png)
[脑图](https://shimo.im/mindmaps/w9wxWqVhhwGVd9vr/ 《数据结构脑图》，可复制链接后用石墨文档 App 或小程序打开)
1. 先来自我介绍一段
  我是一位上海的打工仔兼两个调皮鬼的爸爸。就职于一家中小自媒体公司，担任10小团队的leader，每天付出12个小时却迟迟得不到上级的诺言兑现（一鼓作气，再而衰，三而竭。身心疲惫）。竖子不足与谋！准备脱坑。希望在此结实优秀的技术小伙伴~
2. 我非常赞同老师反复强调的构建脑图的观点。脑图，我更喜欢理解成个人的知识理论体系架构，看似对我的实际工作没什么帮助，冥冥之中却是指明解决问题的道路。我这张残破的图往往令我迷惘。尤其到了需要考虑性能的时候突出。
3. 链接是我不依赖于任何资料绘制的。上面有很多缺失的部分或者是错误的地方。
-------------------------------------------Flag-------------------------------------------------------------
此issue立为flag，8周的时间内不断的完善这张图。课程结束以后这张图就是我最好的成绩单。

4. 另外附上我家宝贝的照片
![image](https://user-images.githubusercontent.com/23305617/70384477-f2b7d700-19b9-11ea-9038-15dd28986bd3.png)

**Comment by sammok** [comment]
哈哈哈哈 两个小机灵鬼儿子

**Comment by highgerms** [comment]
haha
little dogs
